### ISSUE TITLE
Make the package tree-shakable

### ISSUE THREAD

**Issue by niels-bosman** [jetvil/core#1]
@m10rten 

It looks like all of the JavaScript in this library can be imported by importing from the "@jetvil/core" namespace by destructuring the contents. This means, that all of the functions are being loaded whilst someone may only need one of them.

Because if this I think it could be great to structure the project in a way that it is tree-shakable. Here an example of how [Lodash](https://lodash.com/) does this.

You can either import it all from one file (old and slow because all of lodash is loaded).

```js
import { map } from 'lodash';
```

But it's better to only load the file that includes the files necessary for the function.

```js
import map from 'lodash/map';
```

Right now this might not be a huge problem because the amount of utility functions is not enormous, but if you want the package to scale I highly advice for you to rethink your structure.

**Comment by m10rten** [comment]
That is a fair point @niels-bosman I happen to have thought about this topic while working on another project.

Whenever I got the time, I will take this in, but feel free to make a PR fixing this.
After all, its open source contribution😁

**Comment by m10rten** [comment]
Note to this: I've made the folder structure to have `lib/*` for example, types is just 1 part of this.
lib is a part of the `@jetvil` space, where there will be `cli` and perhaps more.

**Comment by m10rten** [comment]
Will close this, the core package is not meant to replace the `types` package, that said, it is possible to have 100+ files for just 1 export each from external packages.
